version: "3.9"
services:
  backend:
    build:
      context: ./server
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:ippdbdmbbmbu@db:5432/mus_library
  frontend:
    build:
      context: ./client
    ports:
      - "3000:80"
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ippdbdmbbmbu
      POSTGRES_DB: mus_library
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./server/prisma/mus_library.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  postgres_data:

networks:
  default:
    name: my_network
